# Generated by Django 5.0.4 on 2024-04-26 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('date_start', models.DateTimeField(verbose_name='Начало события')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='Окончание события')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Соучастники')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
