# Generated by Django 4.2.11 on 2024-04-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0006_alter_users_name_alter_users_password_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('date_start', models.DateTimeField(verbose_name='Начало события')),
                ('date_finish', models.DateTimeField(verbose_name='Окончание события')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('participants', models.ManyToManyField(to='register.users', verbose_name='Соучастники')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
