# Generated by Django 4.0.4 on 2024-05-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_description_alter_notification_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='#0068FF', max_length=10, verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
