# Generated by Django 4.0.4 on 2024-05-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_description_alter_notification_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание'),
        ),
    ]
