# Generated by Django 4.0.4 on 2024-05-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_description'),
        ('events', '0009_alter_event_description_alter_event_time_finish_and_more'),
    ]

    operations = [
    ]
